import "@/styles/globals.css";

import { Inter, Space_Grotesk } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const space_grotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="lemonade" lang="en">
      <body
        className={`flex h-screen bg-orange-100 ${space_grotesk.className}`}
      >
        <div className="m-auto rounded-2xl max-w-xl bg-white p-10 text-center">
          {children}
        </div>
      </body>
    </html>
  );
}
